version: '3'
services:
  webhook-server:
    build: .
    container_name: webhook-server
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - ~/.ssh:/root/.ssh  # SSH-Schlüssel in den Container mounten